spring:
  profile.active: prod
  datasource:
    url: ${_URL}
    username: ${_USERNAME}
    password: ${_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

server:
  error:
    include-stacktrace: never
api:
  security:
    secret: ${JWT_SECRET}
